# Run `mkdir -p database` before `docker compose up`

version: '3.8'

services:
  front:
    image: mpajuka/front-end
    ports:
      - 3000:5000
  back:
    image: mpajuka/back-end 
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
  redis:
    image: redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    container_name: db_exampleapp_2.8
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database:

