version: '3.8'

services:
  front:
    image: mpajuka/front-end 
    ports:
      - 3000:5000
  back:
    image: mpajuka/back-end 
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis